server:
  port: 8765
spring:
  application:
    name: eshop-datasync-service
  rabbitmq:
    host: 192.168.198.1
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.1:8761/eureka/
feign:
  hystrix:
    enabled: true



