server:
  port: 8766
spring:
  application:
    name: eshop-dataaggr-service
  rabbitmq:
    host: 192.168.198.1
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.1:8761/eureka/